// Generated by tools/publish_champion_edition_assets.py. Do not edit manually.

export const CHAMPION_ARTWORK_BY_EDITION: Record<string, { src: string }> = {
  // images/campeonato_brasileiro_serie_a_2021/018.jpg
  "brasileirao_a::2021": { src: "/images/competition-season/editions/brasileirao_a__2021.jpg" },
  // images/campeonato_brasileiro_serie_a_2022/021.jpg
  "brasileirao_a::2022": { src: "/images/competition-season/editions/brasileirao_a__2022.jpg" },
  // images/campeonato_brasileiro_serie_a_2023/023.jpg
  "brasileirao_a::2023": { src: "/images/competition-season/editions/brasileirao_a__2023.jpg" },
  // images/campeonato_brasileiro_serie_a_2024/012.png
  "brasileirao_a::2024": { src: "/images/competition-season/editions/brasileirao_a__2024.png" },
  // images/campeonato_brasileiro_serie_a_2025/005.jpg
  "brasileirao_a::2025": { src: "/images/competition-season/editions/brasileirao_a__2025.jpg" },
  // images/campeonato_brasileiro_serie_b_2021/011.png
  "brasileirao_b::2021": { src: "/images/competition-season/editions/brasileirao_b__2021.png" },
  // images/campeonato_brasileiro_serie_b_2022/005.jpg
  "brasileirao_b::2022": { src: "/images/competition-season/editions/brasileirao_b__2022.jpg" },
  // images/campeonato_brasileiro_serie_b_2023/007.jpg
  "brasileirao_b::2023": { src: "/images/competition-season/editions/brasileirao_b__2023.jpg" },
  // images/campeonato_brasileiro_serie_b_2024/011.jpg
  "brasileirao_b::2024": { src: "/images/competition-season/editions/brasileirao_b__2024.jpg" },
  // images/campeonato_brasileiro_serie_b_2025/014.jpeg
  "brasileirao_b::2025": { src: "/images/competition-season/editions/brasileirao_b__2025.jpeg" },
  // images/bundesliga_2021_2022/024.jpg
  "bundesliga::2021/2022": { src: "/images/competition-season/editions/bundesliga__2021_2022.jpg" },
  // images/bundesliga_2022_2023/018.jpg
  "bundesliga::2022/2023": { src: "/images/competition-season/editions/bundesliga__2022_2023.jpg" },
  // images/bundesliga_2023_2024/012.jpg
  "bundesliga::2023/2024": { src: "/images/competition-season/editions/bundesliga__2023_2024.jpg" },
  // images/bundesliga_2024_2025/008.jpg
  "bundesliga::2024/2025": { src: "/images/competition-season/editions/bundesliga__2024_2025.jpg" },
  // images/uefa_champions_league_2021_2022/003.jpg
  "champions_league::2021/2022": { src: "/images/competition-season/editions/champions_league__2021_2022.jpg" },
  // images/uefa_champions_league_2022_2023/004.jpeg
  "champions_league::2022/2023": { src: "/images/competition-season/editions/champions_league__2022_2023.jpeg" },
  // images/uefa_champions_league_2023_2024/001.jpeg
  "champions_league::2023/2024": { src: "/images/competition-season/editions/champions_league__2023_2024.jpeg" },
  // images/uefa_champions_league_2024_2025/022.jpg
  "champions_league::2024/2025": { src: "/images/competition-season/editions/champions_league__2024_2025.jpg" },
  // images/copa_do_brasil_2021/001.jpg
  "copa_do_brasil::2021": { src: "/images/competition-season/editions/copa_do_brasil__2021.jpg" },
  // images/copa_do_brasil_2022/025.jpg
  "copa_do_brasil::2022": { src: "/images/competition-season/editions/copa_do_brasil__2022.jpg" },
  // images/copa_do_brasil_2023/007.jpg
  "copa_do_brasil::2023": { src: "/images/competition-season/editions/copa_do_brasil__2023.jpg" },
  // images/copa_do_brasil_2024/019.jpeg
  "copa_do_brasil::2024": { src: "/images/competition-season/editions/copa_do_brasil__2024.jpeg" },
  // images/copa_do_brasil_2025/018.jpg
  "copa_do_brasil::2025": { src: "/images/competition-season/editions/copa_do_brasil__2025.jpg" },
  // images/fifa_intercontinental_cup_2024/001.jpg
  "fifa_intercontinental_cup::2024": { src: "/images/competition-season/editions/fifa_intercontinental_cup__2024.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1930__champion__uruguai__trophy-lift__v01.jpeg
  "fifa_world_cup_mens::1930": { src: "/images/competition-season/editions/fifa_world_cup_mens__1930.jpeg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1934__champion__italia__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1934": { src: "/images/competition-season/editions/fifa_world_cup_mens__1934.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1938__champion__italia__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1938": { src: "/images/competition-season/editions/fifa_world_cup_mens__1938.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1950__champion__uruguai__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1950": { src: "/images/competition-season/editions/fifa_world_cup_mens__1950.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1954__champion__alemanha__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1954": { src: "/images/competition-season/editions/fifa_world_cup_mens__1954.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1958__champion__brasil__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1958": { src: "/images/competition-season/editions/fifa_world_cup_mens__1958.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1962__champion__brasil__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1962": { src: "/images/competition-season/editions/fifa_world_cup_mens__1962.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1966__champion__inglaterra__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1966": { src: "/images/competition-season/editions/fifa_world_cup_mens__1966.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1970__champion__brasil__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1970": { src: "/images/competition-season/editions/fifa_world_cup_mens__1970.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1974__champion__alemanha__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1974": { src: "/images/competition-season/editions/fifa_world_cup_mens__1974.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1978__champion__argentina__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1978": { src: "/images/competition-season/editions/fifa_world_cup_mens__1978.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1982__champion__italia__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1982": { src: "/images/competition-season/editions/fifa_world_cup_mens__1982.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1986__champion__argentina__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1986": { src: "/images/competition-season/editions/fifa_world_cup_mens__1986.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1990__champion__alemanha__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1990": { src: "/images/competition-season/editions/fifa_world_cup_mens__1990.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1994__champion__brasil__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1994": { src: "/images/competition-season/editions/fifa_world_cup_mens__1994.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__1998__champion__franca__trophy-lift__v01.jpg
  "fifa_world_cup_mens::1998": { src: "/images/competition-season/editions/fifa_world_cup_mens__1998.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__2002__champion__brasil__trophy-lift__v01.jpg
  "fifa_world_cup_mens::2002": { src: "/images/competition-season/editions/fifa_world_cup_mens__2002.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__2006__champion__italia__trophy-lift__v01.jpg
  "fifa_world_cup_mens::2006": { src: "/images/competition-season/editions/fifa_world_cup_mens__2006.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__2010__champion__espanha__trophy-lift__v01.jpg
  "fifa_world_cup_mens::2010": { src: "/images/competition-season/editions/fifa_world_cup_mens__2010.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__2014__champion__alemanha__trophy-lift__v01.jpg
  "fifa_world_cup_mens::2014": { src: "/images/competition-season/editions/fifa_world_cup_mens__2014.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__2018__champion__franca__trophy-lift__v01.jpg
  "fifa_world_cup_mens::2018": { src: "/images/competition-season/editions/fifa_world_cup_mens__2018.jpg" },
  // data/visual_assets/champions/fifa_world_cup_mens__2022__champion__argentina__trophy-lift__v01.jpg
  "fifa_world_cup_mens::2022": { src: "/images/competition-season/editions/fifa_world_cup_mens__2022.jpg" },
  // images/la_liga_2021_2022/009.jpg
  "la_liga::2021/2022": { src: "/images/competition-season/editions/la_liga__2021_2022.jpg" },
  // images/la_liga_2022_2023/019.jpeg
  "la_liga::2022/2023": { src: "/images/competition-season/editions/la_liga__2022_2023.jpeg" },
  // images/la_liga_2023_2024/023.jpeg
  "la_liga::2023/2024": { src: "/images/competition-season/editions/la_liga__2023_2024.jpeg" },
  // images/la_liga_2024_2025/020.jpg
  "la_liga::2024/2025": { src: "/images/competition-season/editions/la_liga__2024_2025.jpg" },
  // images/copa_libertadores_da_america_2021/002.jpg
  "libertadores::2021": { src: "/images/competition-season/editions/libertadores__2021.jpg" },
  // images/copa_libertadores_da_america_2022/022.jpg
  "libertadores::2022": { src: "/images/competition-season/editions/libertadores__2022.jpg" },
  // images/copa_libertadores_da_america_2023/007.jpg
  "libertadores::2023": { src: "/images/competition-season/editions/libertadores__2023.jpg" },
  // images/copa_libertadores_da_america_2024/020.jpg
  "libertadores::2024": { src: "/images/competition-season/editions/libertadores__2024.jpg" },
  // images/copa_libertadores_da_america_2025/014.jpg
  "libertadores::2025": { src: "/images/competition-season/editions/libertadores__2025.jpg" },
  // images/ligue_1_2021_2022/005.jpg
  "ligue_1::2021/2022": { src: "/images/competition-season/editions/ligue_1__2021_2022.jpg" },
  // images/ligue_1_2022_2023/012.jpg
  "ligue_1::2022/2023": { src: "/images/competition-season/editions/ligue_1__2022_2023.jpg" },
  // images/ligue_1_2023_2024/018.jpg
  "ligue_1::2023/2024": { src: "/images/competition-season/editions/ligue_1__2023_2024.jpg" },
  // images/ligue_1_2024_2025/014.jpg
  "ligue_1::2024/2025": { src: "/images/competition-season/editions/ligue_1__2024_2025.jpg" },
  // images/premier_league_2021_2022/018.jpg
  "premier_league::2021/2022": { src: "/images/competition-season/editions/premier_league__2021_2022.jpg" },
  // images/premier_league_2022_2023/023.jpg
  "premier_league::2022/2023": { src: "/images/competition-season/editions/premier_league__2022_2023.jpg" },
  // images/premier_league_2023_2024/021.jpeg
  "premier_league::2023/2024": { src: "/images/competition-season/editions/premier_league__2023_2024.jpeg" },
  // images/premier_league_2024_2025/019.jpg
  "premier_league::2024/2025": { src: "/images/competition-season/editions/premier_league__2024_2025.jpg" },
  // images/liga_portugal_2023_2024/016.jpeg
  "primeira_liga::2023/2024": { src: "/images/competition-season/editions/primeira_liga__2023_2024.jpeg" },
  // images/liga_portugal_2024_2025/016.jpg
  "primeira_liga::2024/2025": { src: "/images/competition-season/editions/primeira_liga__2024_2025.jpg" },
  // images/serie_a_italia_2021_2022/018.jpg
  "serie_a_italy::2021/2022": { src: "/images/competition-season/editions/serie_a_italy__2021_2022.jpg" },
  // images/serie_a_italia_2022_2023/001.jfif
  "serie_a_italy::2022/2023": { src: "/images/competition-season/editions/serie_a_italy__2022_2023.jpg" },
  // images/serie_a_italia_2023_2024/020.jpg
  "serie_a_italy::2023/2024": { src: "/images/competition-season/editions/serie_a_italy__2023_2024.jpg" },
  // images/serie_a_italia_2024_2025/004.jpg
  "serie_a_italy::2024/2025": { src: "/images/competition-season/editions/serie_a_italy__2024_2025.jpg" },
  // images/copa_sudamericana_2024/003.jpg
  "sudamericana::2024": { src: "/images/competition-season/editions/sudamericana__2024.jpg" },
  // images/copa_sudamericana_2025/001.jpeg
  "sudamericana::2025": { src: "/images/competition-season/editions/sudamericana__2025.jpeg" },
  // images/supercopa_do_brasil_2025/012.jpg
  "supercopa_do_brasil::2025": { src: "/images/competition-season/editions/supercopa_do_brasil__2025.jpg" },
};
