{{ config(materialized='table', schema='control') }}

with source as (
    select *
    from (
        values
            ('lib_qualification_group_knockout_v1', 10, '1st_round', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', '2nd_round', 'Vencedor da primeira fase avanca para a segunda fase.'),
            ('lib_qualification_group_knockout_v1', 11, '1st_round', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da primeira fase deixa a competicao.'),
            ('lib_qualification_group_knockout_v1', 20, '2nd_round', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', '3rd_round', 'Vencedor da segunda fase avanca para a terceira fase.'),
            ('lib_qualification_group_knockout_v1', 21, '2nd_round', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da segunda fase deixa a competicao.'),
            ('lib_qualification_group_knockout_v1', 30, '3rd_round', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'group_stage', 'Vencedor da terceira fase entra na fase de grupos.'),
            ('lib_qualification_group_knockout_v1', 31, '3rd_round', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'repechage', null, 'Derrotado da terceira fase vai para repescagem externa ao torneio.'),
            ('lib_qualification_group_knockout_v1', 40, 'group_stage', 'group_table', 'group_position', 1, 2, null, 'qualified', 'round_of_16', 'Primeiro e segundo colocados de cada grupo avancam para as oitavas.'),
            ('lib_qualification_group_knockout_v1', 41, 'group_stage', 'group_table', 'group_position', 3, 3, null, 'repechage', null, 'Terceiro colocado segue para repescagem externa ao torneio.'),
            ('lib_qualification_group_knockout_v1', 42, 'group_stage', 'group_table', 'group_position', 4, 4, null, 'eliminated', null, 'Quarto colocado deixa a competicao.'),
            ('lib_qualification_group_knockout_v1', 50, 'round_of_16', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'quarter_finals', 'Vencedor das oitavas avanca para as quartas.'),
            ('lib_qualification_group_knockout_v1', 51, 'round_of_16', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado das oitavas deixa a competicao.'),
            ('lib_qualification_group_knockout_v1', 60, 'quarter_finals', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'semi_finals', 'Vencedor das quartas avanca para a semifinal.'),
            ('lib_qualification_group_knockout_v1', 61, 'quarter_finals', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado das quartas deixa a competicao.'),
            ('lib_qualification_group_knockout_v1', 70, 'semi_finals', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'final', 'Vencedor da semifinal avanca para a final.'),
            ('lib_qualification_group_knockout_v1', 71, 'semi_finals', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da semifinal deixa a competicao.'),
            ('lib_qualification_group_knockout_v1', 80, 'final', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da final deixa a competicao.'),
            ('sud_qualification_group_playoff_knockout_v1', 10, '1st_round', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'group_stage', 'Vencedor da primeira fase entra na fase de grupos.'),
            ('sud_qualification_group_playoff_knockout_v1', 11, '1st_round', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da primeira fase deixa a competicao.'),
            ('sud_qualification_group_playoff_knockout_v1', 20, 'group_stage', 'group_table', 'group_position', 1, 1, null, 'qualified', 'round_of_16', 'Lider de cada grupo avanca direto para as oitavas.'),
            ('sud_qualification_group_playoff_knockout_v1', 21, 'group_stage', 'group_table', 'group_position', 2, 2, null, 'qualified', 'round_of_32', 'Vice-lider segue para o playoff eliminatorio nomeado como round_of_32 nesta edição.'),
            ('sud_qualification_group_playoff_knockout_v1', 22, 'group_stage', 'group_table', 'group_position', 2, 2, null, 'qualified', 'knockout_round_play_offs', 'Vice-lider segue para o playoff eliminatorio nomeado como knockout_round_play_offs nesta edição.'),
            ('sud_qualification_group_playoff_knockout_v1', 23, 'group_stage', 'group_table', 'group_position', 3, 4, null, 'eliminated', null, 'Times fora do top 2 deixam a competicao principal.'),
            ('sud_qualification_group_playoff_knockout_v1', 30, 'round_of_32', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'round_of_16', 'Vencedor do playoff eliminatorio avanca para as oitavas.'),
            ('sud_qualification_group_playoff_knockout_v1', 31, 'round_of_32', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado do playoff eliminatorio deixa a competicao.'),
            ('sud_qualification_group_playoff_knockout_v1', 32, 'knockout_round_play_offs', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'round_of_16', 'Vencedor do playoff eliminatorio avanca para as oitavas.'),
            ('sud_qualification_group_playoff_knockout_v1', 33, 'knockout_round_play_offs', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado do playoff eliminatorio deixa a competicao.'),
            ('sud_qualification_group_playoff_knockout_v1', 40, 'round_of_16', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'quarter_finals', 'Vencedor das oitavas avanca para as quartas.'),
            ('sud_qualification_group_playoff_knockout_v1', 41, 'round_of_16', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado das oitavas deixa a competicao.'),
            ('sud_qualification_group_playoff_knockout_v1', 50, 'quarter_finals', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'semi_finals', 'Vencedor das quartas avanca para a semifinal.'),
            ('sud_qualification_group_playoff_knockout_v1', 51, 'quarter_finals', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado das quartas deixa a competicao.'),
            ('sud_qualification_group_playoff_knockout_v1', 60, 'semi_finals', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'final', 'Vencedor da semifinal avanca para a final.'),
            ('sud_qualification_group_playoff_knockout_v1', 61, 'semi_finals', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da semifinal deixa a competicao.'),
            ('sud_qualification_group_playoff_knockout_v1', 70, 'final', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', null, 'Vencedor da final encerra a edição como campeao.'),
            ('sud_qualification_group_playoff_knockout_v1', 71, 'final', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da final deixa a competicao.'),
            ('ucl_group_knockout_v1', 10, 'preliminary_round_semi_finals', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'preliminary_round_final', 'Vencedor da semifinal preliminar avanca para a final preliminar.'),
            ('ucl_group_knockout_v1', 11, 'preliminary_round_semi_finals', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'repechage', null, 'Derrotado da semifinal preliminar sai da edição principal.'),
            ('ucl_group_knockout_v1', 20, 'preliminary_round_final', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', '1st_qualifying_round', 'Vencedor da final preliminar avanca para a primeira fase qualificatoria.'),
            ('ucl_group_knockout_v1', 21, 'preliminary_round_final', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'repechage', null, 'Derrotado da final preliminar sai da edição principal.'),
            ('ucl_group_knockout_v1', 30, '1st_qualifying_round', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', '2nd_qualifying_round', 'Vencedor da primeira qualificatoria avanca para a segunda.'),
            ('ucl_group_knockout_v1', 31, '1st_qualifying_round', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'repechage', null, 'Derrotado da primeira qualificatoria sai da edição principal.'),
            ('ucl_group_knockout_v1', 40, '2nd_qualifying_round', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', '3rd_qualifying_round', 'Vencedor da segunda qualificatoria avanca para a terceira.'),
            ('ucl_group_knockout_v1', 41, '2nd_qualifying_round', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'repechage', null, 'Derrotado da segunda qualificatoria sai da edição principal.'),
            ('ucl_group_knockout_v1', 50, '3rd_qualifying_round', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'play_offs', 'Vencedor da terceira qualificatoria avanca para os play-offs.'),
            ('ucl_group_knockout_v1', 51, '3rd_qualifying_round', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'repechage', null, 'Derrotado da terceira qualificatoria sai da edição principal.'),
            ('ucl_group_knockout_v1', 60, 'play_offs', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'group_stage', 'Vencedor dos play-offs entra na fase de grupos.'),
            ('ucl_group_knockout_v1', 61, 'play_offs', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'repechage', null, 'Derrotado dos play-offs sai da edição principal.'),
            ('ucl_group_knockout_v1', 70, 'group_stage', 'group_table', 'group_position', 1, 2, null, 'qualified', 'round_of_16', 'Primeiro e segundo colocados avancam ao mata-mata.'),
            ('ucl_group_knockout_v1', 71, 'group_stage', 'group_table', 'group_position', 1, 2, null, 'qualified', '8th_finals', 'Primeiro e segundo colocados avancam ao mata-mata.'),
            ('ucl_group_knockout_v1', 72, 'group_stage', 'group_table', 'group_position', 3, 3, null, 'repechage', null, 'Terceiro colocado vai para competicao externa.'),
            ('ucl_group_knockout_v1', 73, 'group_stage', 'group_table', 'group_position', 4, 4, null, 'eliminated', null, 'Quarto colocado deixa a competicao.'),
            ('ucl_group_knockout_v1', 80, 'round_of_16', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'quarter_finals', 'Vencedor das oitavas avanca para as quartas.'),
            ('ucl_group_knockout_v1', 81, 'round_of_16', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado das oitavas deixa a competicao.'),
            ('ucl_group_knockout_v1', 82, '8th_finals', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'quarter_finals', 'Vencedor das oitavas avanca para as quartas.'),
            ('ucl_group_knockout_v1', 83, '8th_finals', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado das oitavas deixa a competicao.'),
            ('ucl_group_knockout_v1', 90, 'quarter_finals', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'semi_finals', 'Vencedor das quartas avanca para a semifinal.'),
            ('ucl_group_knockout_v1', 91, 'quarter_finals', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado das quartas deixa a competicao.'),
            ('ucl_group_knockout_v1', 100, 'semi_finals', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'final', 'Vencedor da semifinal avanca para a final.'),
            ('ucl_group_knockout_v1', 101, 'semi_finals', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da semifinal deixa a competicao.'),
            ('ucl_group_knockout_v1', 110, 'final', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da final deixa a competicao.'),
            ('ucl_league_table_knockout_v1', 10, '1st_qualifying_round', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', '2nd_qualifying_round', 'Vencedor da primeira qualificatoria avanca para a segunda.'),
            ('ucl_league_table_knockout_v1', 11, '1st_qualifying_round', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'repechage', null, 'Derrotado da primeira qualificatoria sai da edição principal.'),
            ('ucl_league_table_knockout_v1', 20, '2nd_qualifying_round', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', '3rd_qualifying_round', 'Vencedor da segunda qualificatoria avanca para a terceira.'),
            ('ucl_league_table_knockout_v1', 21, '2nd_qualifying_round', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'repechage', null, 'Derrotado da segunda qualificatoria sai da edição principal.'),
            ('ucl_league_table_knockout_v1', 30, '3rd_qualifying_round', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'play_offs', 'Vencedor da terceira qualificatoria avanca para os play-offs.'),
            ('ucl_league_table_knockout_v1', 31, '3rd_qualifying_round', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'repechage', null, 'Derrotado da terceira qualificatoria sai da edição principal.'),
            ('ucl_league_table_knockout_v1', 40, 'play_offs', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'league_stage', 'Vencedor dos play-offs entra na league phase.'),
            ('ucl_league_table_knockout_v1', 41, 'play_offs', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'repechage', null, 'Derrotado dos play-offs sai da edição principal.'),
            ('ucl_league_table_knockout_v1', 50, 'league_stage', 'league_table', 'table_position', 1, 8, null, 'qualified', 'round_of_16', 'Top 8 da league phase avancam direto para as oitavas.'),
            ('ucl_league_table_knockout_v1', 51, 'league_stage', 'league_table', 'table_position', 9, 24, null, 'qualified', 'knockout_round_play_offs', 'Posicoes 9 a 24 disputam o playoff eliminatorio.'),
            ('ucl_league_table_knockout_v1', 52, 'league_stage', 'league_table', 'table_position', 25, 36, null, 'eliminated', null, 'Posicoes 25 a 36 deixam a competicao.'),
            ('ucl_league_table_knockout_v1', 60, 'knockout_round_play_offs', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'round_of_16', 'Vencedor do playoff avancam para as oitavas.'),
            ('ucl_league_table_knockout_v1', 61, 'knockout_round_play_offs', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado do playoff deixa a competicao.'),
            ('ucl_league_table_knockout_v1', 70, 'round_of_16', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'quarter_finals', 'Vencedor das oitavas avanca para as quartas.'),
            ('ucl_league_table_knockout_v1', 71, 'round_of_16', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado das oitavas deixa a competicao.'),
            ('ucl_league_table_knockout_v1', 80, 'quarter_finals', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'semi_finals', 'Vencedor das quartas avanca para a semifinal.'),
            ('ucl_league_table_knockout_v1', 81, 'quarter_finals', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado das quartas deixa a competicao.'),
            ('ucl_league_table_knockout_v1', 90, 'semi_finals', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'final', 'Vencedor da semifinal avanca para a final.'),
            ('ucl_league_table_knockout_v1', 91, 'semi_finals', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da semifinal deixa a competicao.'),
            ('ucl_league_table_knockout_v1', 100, 'final', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da final deixa a competicao.'),
            ('fic_annual_champions_knockout_v1', 10, '1st_round', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', '2nd_round', 'Vencedor da primeira fase avanca para a segunda fase.'),
            ('fic_annual_champions_knockout_v1', 11, '1st_round', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da primeira fase deixa a competicao.'),
            ('fic_annual_champions_knockout_v1', 20, '2nd_round', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'play_off', 'Vencedores da segunda fase avancam para o playoff decisivo.'),
            ('fic_annual_champions_knockout_v1', 21, '2nd_round', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da segunda fase deixa a competicao.'),
            ('fic_annual_champions_knockout_v1', 30, 'play_off', 'qualification_knockout', 'tie_outcome', null, null, 'winner', 'qualified', 'final', 'Vencedor do playoff avanca para a final.'),
            ('fic_annual_champions_knockout_v1', 31, 'play_off', 'qualification_knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado do playoff deixa a competicao.'),
            ('fic_annual_champions_knockout_v1', 40, 'final', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', null, 'Vencedor da final encerra a edição como campeao.'),
            ('fic_annual_champions_knockout_v1', 41, 'final', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da final deixa a competicao.'),
            ('supercopa_single_final_v1', 10, 'final', 'knockout', 'tie_outcome', null, null, 'winner', 'qualified', null, 'Vencedor da final encerra a edição como campeao.'),
            ('supercopa_single_final_v1', 11, 'final', 'knockout', 'tie_outcome', null, null, 'loser', 'eliminated', null, 'Derrotado da final encerra a edição como vice-campeao.')
    ) as seeded (
        season_format_code,
        rule_order,
        from_stage_code,
        from_stage_format,
        progression_scope,
        position_from,
        position_to,
        tie_outcome,
        progression_type,
        to_stage_code,
        notes
    )
)
select
    trim(season_format_code) as season_format_code,
    rule_order,
    trim(from_stage_code) as from_stage_code,
    trim(from_stage_format) as from_stage_format,
    trim(progression_scope) as progression_scope,
    position_from,
    position_to,
    nullif(trim(tie_outcome), '') as tie_outcome,
    trim(progression_type) as progression_type,
    nullif(trim(to_stage_code), '') as to_stage_code,
    trim(notes) as notes,
    now() as updated_at
from source
