version: 2

sources:
  - name: postgres_raw
    database: "{{ env_var('FOOTBALL_PG_DBNAME', env_var('POSTGRES_DB', 'football_dw')) }}"
    schema: raw
    tables:
      - name: fixtures
      - name: match_statistics
      - name: match_events
      - name: competition_leagues
      - name: competition_seasons
      - name: competition_stages
      - name: competition_rounds
      - name: standings_snapshots
      - name: fixture_lineups
      - name: fixture_player_statistics
      - name: player_season_statistics
      - name: player_transfers
      - name: team_sidelined
      - name: team_coaches
      - name: coaches
      - name: head_to_head_fixtures
      - name: statsbomb_matches
      - name: statsbomb_events
      - name: statsbomb_lineups
      - name: statsbomb_three_sixty_frames
      - name: statsbomb_three_sixty_freeze_frame

  - name: postgres_mart
    database: "{{ env_var('FOOTBALL_PG_DBNAME', env_var('POSTGRES_DB', 'football_dw')) }}"
    schema: mart
    tables:
      - name: stg_statsbomb_match_identity
      - name: stg_statsbomb_team_identity
      - name: stg_statsbomb_player_identity
